### PR TITLE
add homepage

### PR DESCRIPTION
**Pull request by zubairahad**

### CODE REVIEW

**Comment by UmmarHamid** [comment]
There are previous PR commits in this one as well!.
Did you not follow the steps I mentioned?

**Comment by zubairahad** [comment]
I followed the same steps as you mentioned

**Comment by UmmarHamid** [comment]
why are there previous commits then?

**Comment by UmmarHamid** [comment]
Let me fix the changes myself, we can connect later for more details

**Review by UmmarHamid — APPROVED** [review]
Updated this Pr

**Pull request merged**
